kind: ButtonGroup
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: admin-page-finops-panel-column-row-1-notebooks-button-group
  namespace: {{ .Release.Namespace }}
spec: 
  widgetData:
    allowedResources:
    - buttons
    alignment: right
    gap: small
    items:
      - resourceRefId: filter
      - resourceRefId: create
  resourcesRefs:
    items:
    - id: filter
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: admin-page-finops-filter-button
      namespace: {{ .Release.Namespace }}
      resource: buttons
      verb: GET
    - id: create
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: admin-page-finops-upload-panel-button
      namespace: {{ .Release.Namespace }}
      resource: buttons
      verb: GET