kind: Filters
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: admin-page-finops-filter-button-filters
spec:
  widgetData:
    prefix: admin-page-finops
    fields:
    - label: Name
      type: string
      name: 
        - name
    - label: Namespace
      type: string
      name: 
        - namespace