kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: admin-page-finops-panel-row-1-notebooks-panel
  namespace: {{ .Release.Namespace }}
spec: 
  widgetData:
    actions: {}
    title: Notebooks
    items:
      - resourceRefId: panel-notebooks
      - resourceRefId: table
  resourcesRefs:
    items:
    - id:  panel-notebooks
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: admin-page-finops-panel-row-1f-filter-button
      namespace: {{ .Release.Namespace }}
      resource: buttons
      verb: GET
    - id: table
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: admin-page-finops-panel-row-1-notebooks-panel-table
      namespace: {{ .Release.Namespace }}
      resource: tables
      verb: GET