apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  annotations:
    krateo.io/verbose: "true"
  name: admin-page-finops-panel-row-1-list-notebooks-and-buttons
  namespace: {{ .Release.Namespace }}
spec:
  api:
  - name: getNotebooks
    endpointRef:
      name: resources-presenter-endpoint
      namespace: krateo-system
    path: "/resources?group=finops.krateo.io&version=v1&namespace=*&resource=notebooks&limit=5000"
    verb: GET 
    continueOnError: true
    exportJwt: true
    errorKey: getNotebooksError
    filter: "[ .getNotebooks.items[] | {name: .name, namespace: .namespace}]"
  - name: getButtons
    endpointRef:
      name: resources-presenter-endpoint
      namespace: krateo-system
    path: "/resources?group=widgets.templates.krateo.io&version=v1beta1&namespace=*&resource=buttons&limit=5000"
    verb: GET 
    continueOnError: true
    exportJwt: true
    errorKey: getButtonsError
    filter: "[ .getButtons.items[] | {name: .name, namespace: .namespace}]"
  filter: >
    (.getButtons // []) as $b
    | (.getNotebooks // []) as $p
    | {
        buttonsToCreate: (
          $p
          | map(select(
              (.name, .namespace) as $ppair
              | all($b[]; (.name, .namespace) != $ppair)
            ))
          | unique_by(.name, .namespace)
        ),
        buttonsToDelete: (
          $b
          | map(select(
              (.name, .namespace) as $bpair
              | all($p[]; (.name, .namespace) != $bpair)
            ))
          | unique_by(.name, .namespace)
        )
      }
---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  annotations:
    krateo.io/verbose: "true"
  name: admin-page-finops-panel-row-1-list-notebooks-and-paragraphs
  namespace: {{ .Release.Namespace }}
spec:
  api:
  - name: getNotebooks
    endpointRef:
      name: resources-presenter-endpoint
      namespace: krateo-system
    path: "/resources?group=finops.krateo.io&version=v1&namespace=*&resource=notebooks&limit=5000"
    verb: GET 
    continueOnError: true
    exportJwt: true
    errorKey: getNotebooksError
    filter: "[ .getNotebooks.items[] | {name: .name, namespace: .namespace}]"
  - name: getParagraphs
    endpointRef:
      name: resources-presenter-endpoint
      namespace: krateo-system
    path: "/resources?group=widgets.templates.krateo.io&version=v1beta1&namespace=*&resource=paragraphs&limit=5000"
    verb: GET 
    continueOnError: true
    exportJwt: true
    errorKey: getParagraphsError
    filter: "[ .getParagraphs.items[] | {name: .name, namespace: .namespace}]"
  filter: >
    (.getParagraphs // []) as $b
    | (.getNotebooks // []) as $p
    | {
        paragraphsToCreate: (
          $p
          | map(select(
              (.name, .namespace) as $ppair
              | all($b[]; (.name, .namespace) != $ppair)
            ))
          | unique_by(.name, .namespace)
        ),
        paragraphsToDelete: (
          $b
          | map(select(
              (.name, .namespace) as $bpair
              | all($p[]; (.name, .namespace) != $bpair)
            ))
          | unique_by(.name, .namespace)
        )
      }
---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  annotations:
    krateo.io/verbose: "true"
  name: admin-page-finops-panel-row-1-list-notebooks-and-restactions
  namespace: {{ .Release.Namespace }}
spec:
  api:
  - name: getNotebooks
    endpointRef:
      name: resources-presenter-endpoint
      namespace: krateo-system
    path: "/resources?group=finops.krateo.io&version=v1&namespace=*&resource=notebooks&limit=5000"
    verb: GET 
    continueOnError: true
    exportJwt: true
    errorKey: getNotebooksError
    filter: "[ .getNotebooks.items[] | {name: .name, namespace: .namespace}]"
  - name: getRestActions
    endpointRef:
      name: resources-presenter-endpoint
      namespace: krateo-system
    path: "/resources?group=templates.krateo.io&version=v1&namespace=*&resource=restactions&limit=5000"
    verb: GET 
    continueOnError: true
    exportJwt: true
    errorKey: getRestActionsError
    filter: "[ .getRestActions.items[] | {name: .name, namespace: .namespace}]"
  filter: >
    (.getRestActions // []) as $b
    | (.getNotebooks // []) as $p
    | {
        restActionsToCreate: (
          $p
          | map(select(
              (.name, .namespace) as $ppair
              | all($b[]; (.name, .namespace) != $ppair)
            ))
          | unique_by(.name, .namespace)
        ),
        restActionsToDelete: (
          $b
          | map(select(
              (.name, .namespace) as $bpair
              | all($p[]; (.name, .namespace) != $bpair)
            ))
          | unique_by(.name, .namespace)
        )
      }
---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  annotations:
    krateo.io/verbose: "true"
  name: admin-page-finops-panel-row-1-list-notebooks-and-create
  namespace: {{ .Release.Namespace }}
spec:
  api:
  - name: listNotebooksAndButtons
    path: "/call?apiVersion=templates.krateo.io/v1&resource=restactions&name=admin-page-finops-panel-row-1-list-notebooks-and-buttons&namespace={{ .Release.Namespace }}"
    verb: GET
    endpointRef:
      name: snowplow-endpoint
      namespace: {{ .Release.Namespace }}
    headers:
    - 'Accept: application/json'
    continueOnError: true
    errorKey: listNotebooksAndButtonsError
    exportJwt: true
    filter: ".listNotebooksAndButtons.status? // {}"
  - name: listNotebooksAndParagraphs
    path: "/call?apiVersion=templates.krateo.io/v1&resource=restactions&name=admin-page-finops-panel-row-1-list-notebooks-and-paragraphs&namespace={{ .Release.Namespace }}"
    verb: GET
    endpointRef:
      name: snowplow-endpoint
      namespace:  {{ .Release.Namespace }}
    headers:
    - 'Accept: application/json'
    continueOnError: true
    errorKey: listNotebooksAndParagraphsError
    exportJwt: true
    filter: ".listNotebooksAndParagraphs.status? // {}"
  - name: listNotebooksAndRestActions
    path: "/call?apiVersion=templates.krateo.io/v1&resource=restactions&name=admin-page-finops-panel-row-1-list-notebooks-and-restactions&namespace={{ .Release.Namespace }}"
    verb: GET
    endpointRef:
      name: snowplow-endpoint
      namespace:  {{ .Release.Namespace }}
    headers:
    - 'Accept: application/json'
    continueOnError: true
    errorKey: listNotebooksAndRestActionsError
    exportJwt: true
    filter: ".listNotebooksAndRestActions.status? // {}"
  - name: createButton
    continueOnError: true
    errorKey: createButtonError
    dependsOn: 
      name: listNotebooksAndButtons
      iterator: .listNotebooksAndButtons.buttonsToCreate
    path: ${ "/apis/widgets.templates.krateo.io/v1beta1/namespaces/" + (.namespace ) + "/buttons/" }
    verb: POST
    headers:
      - "Content-Type: application/json"
    payload: |
      ${
        {
          "kind": "Button",
          "apiVersion": "widgets.templates.krateo.io/v1beta1",
          "metadata": {
            "name": .name,
            "namespace": .namespace,
            "labels": {
              "krateo.io/portal": "button-for-table"
            }
          },
          "spec": {
            "widgetData": {
              "label": "Code",
              "icon": "fa-solid fa-list",
              "size": "middle",
              "type": "primary",
              "clickActionId": "open",
              "actions": {
                "openModal": [
                  {
                    "id": "open",
                    "resourceRefId": "paragraph",
                    "type": "openModal",
                    "title": "Notebook Code: " + .name,
                    "size": "large"
                  }
                ]
              }
            },
            "resourcesRefs": {
              "items": [
                {
                  "id": "paragraph",
                  "apiVersion": "widgets.templates.krateo.io/v1beta1",
                  "resource": "markdowns",
                  "name": .name,
                  "namespace": .namespace,
                  "verb": "GET"
                }
              ]
            }
          }
        }
      }
  - name: createParagraphs
    continueOnError: true
    errorKey: createParagraphError
    dependsOn: 
      name: listNotebooksAndParagraphs
      iterator: .listNotebooksAndParagraphs.paragraphsToCreate
    path: ${ "/apis/widgets.templates.krateo.io/v1beta1/namespaces/" + (.namespace ) + "/markdowns/" }
    verb: POST
    headers:
      - "Content-Type: application/json"
    payload: |
      ${
        {
          "kind": "Markdown",
          "apiVersion": "widgets.templates.krateo.io/v1beta1",
          "metadata": {
            "name": .name,
            "namespace": .namespace,
            "labels": {
              "krateo.io/portal": "paragraph-for-table"
            }
          },
          "spec": {
            "widgetData": {
              "markdown": "",
              "allowCopy": true,
              "allowDownload": true,
              "downloadFileExtension": "py"
            },
            "widgetDataTemplate": [
              {
                "forPath": "markdown",
                "expression": "${ \"```python\n\" + .notebook.code }"
              }
            ],
            "apiRef": {
              "name": .name,
              "namespace": .namespace
            }
          }
        }
      }
  - name: createRestActions
    continueOnError: true
    errorKey: createRestActionsError
    dependsOn: 
      name: listNotebooksAndRestActions
      iterator: .listNotebooksAndRestActions.restActionsToCreate
    path: ${ "/apis/templates.krateo.io/v1/namespaces/" + (.namespace ) + "/restactions/" }
    verb: POST
    headers:
      - "Content-Type: application/json"
    payload: |
      ${
        {
          "kind": "RESTAction",
          "apiVersion": "templates.krateo.io/v1",
          "metadata": {
            "name": .name,
            "namespace": .namespace,
            "labels": {
              "krateo.io/portal": "restaction-for-table"
            }
          },
          "spec": {
            "api": [
              {
                "name": "notebook",
                "path": "/compute/" + .name + "/info",
                "verb": "GET",
                "endpointRef": {
                  "name": "finops-database-handler-endpoint",
                  "namespace": "{{ .Values.global.krateoNamespace }}"
                }
              }
            ]
          }
        }
      }
---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: admin-page-finops-panel-column-row-1-notebooks-table
  namespace: {{ .Release.Namespace }}
spec:
  api:
  - name: notebooks
    endpointRef:
      name: resources-presenter-endpoint
      namespace: krateo-system
    path: "/resources?group=finops.krateo.io&version=v1&namespace=*&resource=notebooks&limit=5000&raw=true"
    verb: GET 
    continueOnError: true
    exportJwt: true
    errorKey: notebooksError
    filter: "[ .notebooks.items[] | .raw ]"
    continueOnError: true
  - name: createAll
    path: "/call?apiVersion=templates.krateo.io/v1&resource=restactions&name=admin-page-finops-panel-row-1-list-notebooks-and-create&namespace={{ .Release.Namespace }}"
    verb: GET
    endpointRef:
      name: snowplow-endpoint
      namespace: {{ .Release.Namespace }}
    headers:
    - 'Accept: application/json'
    continueOnError: true
    errorKey: createAllError
    exportJwt: true
    dependsOn: 
      name: notebooks
  filter: >
    {
      notebooks: .notebooks,
      list: (
        (
        .notebooks
        | map({
            name: .metadata.name,
            namespace: .metadata.namespace,
            status: (
              if (.status.conditions | type) == "array" then
                ( [.status.conditions[]? | select(.type == "Ready") | "Ready: " + .status ] | first? ) // 
                ( [.status.conditions[]? | select(.type == "Synced") | "Synced: " + .status] | first? // "Status not available" )
              else
                "Status not available"
              end
            )
          })
        | sort_by(.name)
        | map([
            {
              valueKey: "name",
              kind: "jsonSchemaType",
              type: "string",
              stringValue: .name
            },
            {
              valueKey: "namespace",
              kind: "jsonSchemaType",
              type: "string",
              stringValue: .namespace
            },
            {
              valueKey: "status",
              kind: "jsonSchemaType",
              type: "string",
              stringValue: .status
            },
            {
              valueKey: "view",
              kind: "widget",
              resourceRefId: .name
            }
          ])
        )
      )
    }
