apiVersion: widgets.templates.krateo.io/v1beta1
kind: Table
metadata:
  name: admin-page-finops-panel-row-1-notebooks-panel-table
  namespace: {{ .Release.Namespace }}
spec:
  apiRef:
    name: admin-page-finops-panel-row-1-notebooks-panel-table
    namespace: {{ .Release.Namespace }}
  widgetData:
    allowedResources:
    - buttons
    prefix: admin-page-finops
    columns:
    - title: Name
      valueKey: name
    - title: Namespace
      valueKey: namespace
    - title: Status
      valueKey: status  
    - title: View
      valueKey: view
    data: []
    pageSize: 10
  widgetDataTemplate:
  - expression: ${ .list }
    forPath: data
  resourcesRefsTemplate:
    - iterator: ${ .notebooks }
      template:
        id: ${ .metadata.name }
        apiVersion: widgets.templates.krateo.io/v1beta1
        resource: buttons
        namespace: ${ .metadata.namespace }
        name: ${ .metadata.name }
        verb: GET