kind: Form
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: admin-page-users-panel-column-c-create-role-binding-button-form
spec:
  widgetData:
    submitActionId: role
    stringSchema: |
        {
          "properties": {
            "metadata": {
              "properties": {
                "name": {
                  "type": "string"
                },
                "namespace": {
                  "type": "string",
                  "default": "{{ .Release.Namespace }}"
                }
              },
              "type": "object",
              "required": [
                "name",
                "namespace"
              ]
            },
            "rules": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "roleRef": {
                    "type": "object",
                    "required": ["apiGroup", "kind", "name"],
                    "properties": {
                      "apiGroup": {
                        "type": "string",
                        "enum": ["rbac.authorization.k8s.io"]
                      },
                      "kind": {
                        "type": "string",
                        "enum": ["Role", "ClusterRole"]
                      },
                      "name": {
                        "type": "string",
                        "minLength": 1
                      }
                    }
                  },
                  "subjects": {
                    "type": "object",
                    "required": ["kind", "name"],
                    "properties": {
                      "kind": {
                        "type": "string",
                        "enum": ["User", "Group", "ServiceAccount"]
                      },
                      "name": {
                        "type": "string",
                        "minLength": 1
                      },
                      "namespace": {
                        "type": "string",
                        "minLength": 1
                      }
                    }
                  },
                  "required": ["roleRef", "subjects"]
                }
              }
            }
          },
          "required": [
            "metadata",
            "rules"
          ],
          "type": "object"
        }
    objectFields:
      - path: "rules"
        displayField: subjects.name
    actions:
      rest:
        - id: role
          resourceRefId: resource-ref-1
          type: rest
          headers:
          - "content-type: application/json"
  resourcesRefs:
    items:
    - id: resource-ref-1
      apiVersion: rbac.authorization.k8s.io/v1
      resource: rolebindings
      verb: POST