kind: Form
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: admin-page-users-column-panel-c-create-password-button-form
spec:
  widgetData:
    submitActionId: secret
    stringSchema: |
          {
            "properties": {
              "metadata": {
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "namespace": {
                    "type": "string",
                    "default": "{{ .Release.Namespace }}"
                  }
                },
                "type": "object",
                "required": [
                  "name",
                  "namespace"
                ]
              }, 
              "password": {
                  "description": "The password to put into the secret under key: \"password\"",
                  "type": "string"
              }
            },
            "required": [
                "password"
            ],
            "type": "object"
          }
    actions:
      rest:
      - id: secret
        resourceRefId: resource-ref-1
        type: rest
        payloadToOverride:
        - name: stringData
          value: ${ .json }
        - name: metadata.name
          value: ${ .json.metadata.name }
        - name: metadata.namespace
          value: ${ .json.metadata.namespace }
        headers:
        - "content-type: application/json"
  resourcesRefs:
    items:
    - id: resource-ref-1
      apiVersion: v1
      resource: secrets
      verb: POST