kind: Form
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: admin-page-users-column-panel-c-create-role-button-form
spec:
  widgetData:
    submitActionId: role
    stringSchema: |
        {
          "properties": {
            "metadata": {
              "properties": {
                "name": {
                  "type": "string"
                },
                "namespace": {
                  "type": "string",
                  "default": "{{ .Release.Namespace }}"
                }
              },
              "type": "object",
              "required": [
                "name",
                "namespace"
              ]
            },
            "rules": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "apiGroups": {
                    "type": "array",
                    "items": { "type": "string" }
                  },
                  "resources": {
                    "type": "array",
                    "items": { "type": "string" }
                  },
                  "verbs": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "enum": [
                        "get",
                        "list",
                        "watch",
                        "create",
                        "update",
                        "patch",
                        "delete"
                      ]
                    }
                  }
                }
              },
              "required": [
                "apiGroups", 
                "resources",
                "verbs"
              ]
            }
          },
          "required": [
            "metadata",
            "rules"
          ],
          "type": "object"
        }
    objectFields:
      - path: "rules"
        displayField: resources[0]
    actions:
      rest:
        - id: role
          resourceRefId: resource-ref-1
          type: rest
          headers:
          - "content-type: application/json"
  resourcesRefs:
    items:
    - id: resource-ref-1
      apiVersion: rbac.authorization.k8s.io/v1
      resource: roles
      verb: POST