kind: Form
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: admin-page-users-panel-column-c-create-password-button-form
spec:
  widgetData:
    allowedResources:
    - secrets
    submitActionId: secret
    stringSchema: |
          {
            "properties": {
              "metadata": {
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "namespace": {
                    "type": "string",
                    "default": "{{ .Release.Namespace }}"
                  }
                },
                "type": "object",
                "required": [
                  "name",
                  "namespace"
                ]
              }, 
              "password": {
                  "description": "The password to put into the secret under key: \"password\"",
                  "type": "string"
              }
            },
            "required": [
                "password"
            ],
            "type": "object"
          }
    actions:
      rest:
        - id: secret
          resourceRefId: resource-ref-1
          type: rest
          payloadKey: stringData
          payloadToOverride:
          - name: metadata.name
            value: ${ metadata.name }
          - name: metadata.namespace
            value: ${ metadata.namespace }
          headers:
          - "content-type: application/json"
  resourcesRefs:
    items:
    - id: resource-ref-1
      apiVersion: v1
      resource: secrets
      verb: POST