kind: Column
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: admin-page-users-column-panel-c
spec:
  widgetData:
    allowedResources:
    - buttons
    items:
      - resourceRefId: create-password
      - resourceRefId: create-user
      - resourceRefId: create-role
      - resourceRefId: create-role-binding
  resourcesRefs:
    items:
    - id:  create-password
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: admin-page-users-column-panel-c-create-password-button
      namespace: {{ .Release.Namespace }}
      resource: buttons
      verb: GET
    - id:  create-user
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: admin-page-users-column-panel-c-create-user-button
      namespace: {{ .Release.Namespace }}
      resource: buttons
      verb: GET
    - id:  create-role
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: admin-page-users-column-panel-c-create-role-button
      namespace: {{ .Release.Namespace }}
      resource: buttons
      verb: GET
    - id:  create-role-binding
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: admin-page-users-column-panel-c-create-role-binding-button
      namespace: {{ .Release.Namespace }}
      resource: buttons
      verb: GET