kind: Filters
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: admin-page-users-panel-row-2f-filter-button-filters
spec:
  widgetData:
    prefix: admin-page-permissions
    fields:
    - label: Group Name
      type: string
      name: 
        - groupName
    - label: Scope
      type: string
      name: 
        - scope
    - label: Role Name
      type: string
      name: 
        - roleName
    - label: Resources
      type: string
      name: 
        - resources
    - label: Verbs
      type: string
      name: 
        - verbs
    