apiVersion: widgets.templates.krateo.io/v1beta1
kind: Table
metadata:
  name: admin-page-krateo-column-panel-row-1-status-table
  namespace: {{ .Release.Namespace }}
spec:
  apiRef:
    name: admin-page-krateo-column-panel-row-1-status-table
    namespace: {{ .Release.Namespace }}
  widgetData:
    allowedResources: []  
    prefix: admin-page-status
    columns:
    - title: Release Name
      valueKey: releaseName
    - title: Chart Name
      valueKey: chartName
    - title: Chart Version
      valueKey: chartVersion
    - title: URL
      valueKey: url
    data: []
    pageSize: 10
  widgetDataTemplate:
  - forPath: data
    expression: |
      ${
        ( .krateo? // [] )
        | map(
            [
              {valueKey: "releaseName", kind: "jsonSchemaType", type: "string", stringValue: .releaseName},
              {valueKey: "chartName",   kind: "jsonSchemaType", type: "string", stringValue: .chartName},
              {valueKey: "chartVersion",kind: "jsonSchemaType", type: "string", stringValue: .chartVersion},
              {valueKey: "url",      kind: "jsonSchemaType", type: "string", stringValue: .url}
            ]
        )
      }