apiVersion: widgets.templates.krateo.io/v1beta1
kind: Table
metadata:
  name: admin-page-krateo-column-panel-row-2-logs-table
  namespace: {{ .Release.Namespace }}
spec:
  apiRef:
    name: admin-page-krateo-column-panel-row-2-logs-table
    namespace: {{ .Release.Namespace }}
  widgetData:
    actions:
      openModal:
        - id: open-modal-logs
          type: openModal
          size: large
          resourceRefId: ${ .json.name }
          title: Logs
    allowedResources:
    - buttons
    prefix: admin-page-logs
    columns:
    - title: Name
      valueKey: name
    - title: Namespace
      valueKey: namespace
    - title: Status
      valueKey: status  
    - title: Date
      valueKey: date
    data: []
    pageSize: 10
    tableActions:
    - clickActionId: open-modal-logs
      button:
        label: Logs
        icon: fa-solid fa-list
  widgetDataTemplate:
    - forPath: data
      expression: ${ .list }
  resourcesRefsTemplate:
    - iterator: ${ .pods }
      template:
        id: ${ .metadata.name }
        apiVersion: widgets.templates.krateo.io/v1beta1
        resource: markdowns
        namespace: ${ .metadata.namespace }
        name: ${ .metadata.name }
        verb: GET
