kind: Form
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: admin-page-composition-definitions-create-namespace-button-form
spec:
  widgetData:
    submitActionId: namespace
    stringSchema: |
        {
            "properties": {
                "metadata": {
                    "properties": {
                        "name": {
                            "type": "string"
                        }
                    },
                    "type": "object",
                    "required": [
                        "name"
                    ]
                }
            },
            "required": [
                "metadata",
                "type"
            ],
            "type": "object"
        }
    actions:
      rest:
        - id: namespace
          resourceRefId: resource-ref-1
          type: rest
          payloadToOverride:
          - name: metadata.name
            value: ${ metadata.name }
          headers:
          - "content-type: application/json"
  resourcesRefs:
    items:  
    - id: resource-ref-1
      apiVersion: "v1"
      resource: namespaces
      verb: POST