kind: Form
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: admin-page-composition-definitions-create-composition-definition-button-form
spec:
  widgetData:
    submitActionId: compositiondefinition
    stringSchema: |
      {
        "type": "object",
        "properties": {
          "metadata": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "namespace": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "namespace"
            ]
          },
          "chart": {
            "type": "object",
            "properties": {
              "credentials": {
                "description": "credentials for private repos",
                "type": "object",
                "properties": {
                  "passwordRef": {
                    "description": "PasswordRef: reference to secret containing password for private repo",
                    "type": "object",
                    "properties": {
                      "key": {
                        "description": "The key to select.",
                        "type": "string"
                      },
                      "name": {
                        "description": "Name of the referenced object.",
                        "type": "string"
                      },
                      "namespace": {
                        "description": "Namespace of the referenced object.",
                        "type": "string"
                      }
                    }
                  },
                  "username": {
                    "description": "Username: username for private repo",
                    "type": "string"
                  }
                }
              },
              "insecureSkipVerifyTLS": {
                "description": "InsecureSkipVerifyTLS: skip tls verification",
                "type": "boolean"
              },
              "repo": {
                "description": "Repo: helm repo name (for helm repo urls only)",
                "type": "string",
                "maxLength": 256
              },
              "url": {
                "description": "Url: oci or tgz full url",
                "type": "string"
              },
              "version": {
                "description": "Version: desired chart version, needed for oci charts and for helm repo urls",
                "type": "string",
                "maxLength": 20
              }
            },
            "required": [
              "url"
            ]
          }
        },
        "required": [
          "metadata",
          "chart"
        ]
      }
    actions:
      rest:
        - id: compositiondefinition
          resourceRefId: resource-ref-1
          type: rest
          payloadKey: spec
          payloadToOverride:
          - name: metadata.name
            value: ${ metadata.name }
          - name: metadata.namespace
            value: ${ metadata.namespace }
          headers:
          - "content-type: application/json"
  resourcesRefs:
    items:  
    - id: resource-ref-1
      apiVersion: core.krateo.io/v1alpha1
      resource: compositiondefinitions
      verb: POST