apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: admin-page-composition-definitions-column-panel-row-2-composition-definitions-table
  namespace: {{ .Release.Namespace }}
spec:
  api:
  - name: allCompositionDefinitions
    endpointRef:
      name: resources-presenter-endpoint
      namespace: krateo-system
    path: "/resources?group=core.krateo.io&resource=compositiondefinitions&limit=5000&namespace=*&raw=true"
    verb: GET 
    continueOnError: true
    exportJwt: true
    errorKey: allCompositionDefinitionsError
    filter: |
      [ .allCompositionDefinitions | .items[] | .raw ]
