kind: Row
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: admin-page-composition-definitions-panel-column-row-1-namespaces
  namespace: {{ .Release.Namespace }}
spec: 
  widgetData:
    allowedResources:
    - buttons
    - rows
    items:
      - resourceRefId: column-1
        size: 22
      - resourceRefId: create
        size: 1
  resourcesRefs:
    items:
    - id:  column-1
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: empty
      namespace: {{ .Release.Namespace }}
      resource: rows
      verb: GET
    - id:  create
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: admin-page-composition-definitions-create-namespace-button
      namespace: {{ .Release.Namespace }}
      resource: buttons
      verb: GET