apiVersion: widgets.templates.krateo.io/v1beta1
kind: Table
metadata:
  name: admin-page-composition-definitions-column-panel-row-1-namespaces-table
  namespace: {{ .Release.Namespace }}
spec:
  apiRef:
    name: admin-page-composition-definitions-column-panel-row-1-namespaces-table
    namespace: {{ .Release.Namespace }}
  widgetData:
    allowedResources: []  
    columns:
    - title: Name
      valueKey: name
    data: []
    pageSize: 10
  widgetDataTemplate:
    - forPath: data
      expression: |
        ${
          (
            (
              if (.namespaces | type) == "array" then
                [.namespaces[]?.items[]?]
              elif (.namespaces | type) == "object" then
                [.namespaces.items[]?]
              else
                []
              end
            )
            | map({
                name: .metadata.name,
                date: .metadata.creationTimestamp
              })
            | sort_by(.date)
            | reverse
            | map([
                {
                  valueKey: "name",
                  kind: "jsonSchemaType",
                  type: "string",
                  stringValue: .name
                },
                {
                  valueKey: "date",
                  kind: "jsonSchemaType",
                  type: "string",
                  stringValue: .date
                }
              ])
          )
        }