kind: ButtonGroup
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: admin-page-compositions-column-panel-row-2-compositions-button-group
  namespace: {{ .Release.Namespace }}
spec: 
  widgetData:
    allowedResources:
    - buttons
    alignment: right
    gap: small
    items:
      - resourceRefId: filter
      - resourceRefId: create
  resourcesRefs:
    items:
    - id:  filter
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: admin-page-compositions-filter-button-compositions
      namespace: {{ .Release.Namespace }}
      resource: buttons
      verb: GET
    - id:  create
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: admin-page-compositions-go-to-templates-button
      namespace: {{ .Release.Namespace }}
      resource: buttons
      verb: GET