apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: admin-page-compositions-column-panel-row-2-compositions-table
  namespace: {{ .Release.Namespace }}
spec:
  api:
  - name: allCompositions
    endpointRef:
      name: resources-presenter-endpoint
      namespace: krateo-system
    path: "/resources?group=composition.krateo.io&namespace=*&raw=true&limit=5000"
    verb: GET 
    continueOnError: true
    exportJwt: true
    errorKey: allCompositionsError
  filter: |
    {
      allCompositions: ([ .allCompositions | .items[] | .raw ])
    }
