apiVersion: widgets.templates.krateo.io/v1beta1
kind: Table
metadata:
  name: admin-page-compositions-panel-column-row-1-providers-table
  namespace: {{ .Release.Namespace }}
spec:
  apiRef:
    name: admin-page-compositions-panel-column-row-1-providers-table
    namespace: {{ .Release.Namespace }}
  widgetData:
    allowedResources: []  
    prefix: admin-page-providers
    columns:
    - title: Deployment Name
      valueKey: name
    - title: Namespace
      valueKey: namespace
    - title: Status
      valueKey: status
    data: []
    pageSize: 10
  widgetDataTemplate:
    - forPath: data
      expression: ${ .list }