kind: Row
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: empty
  namespace: {{ .Release.Namespace }}
spec: 
  widgetData:
    allowedResources: []
    items: []
  resourcesRefs:
    items: []